build:
  image: chmuul/ansible:$$OS
  pull: true
  commands:
    - ansible-playbook -i tests/inventory tests/main.yml --syntax-check
    - ansible-playbook -i tests/inventory tests/main.yml
matrix:
  OS:
    - ubuntu-16.04
    - debian-8
    - fedora-24
    - centos-7
    - ubuntu-14.04
    - debian-7
