---
- name: purge old docker packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: install requirements
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
#    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker-ce repository (centos7)
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    file: docker

- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: yes

- name: create docker config dir
  file:
    path: /etc/docker
    state: directory

- name: set storage driver
  blockinfile:
    path: /etc/docker/daemon.json
    create: yes
    block: |
      {
        "storage-driver": "devicemapper"
      }
