---
- name: purge old docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: install requirements
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    update_cache: yes

- name: add docker-ce repository (centos7)
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    file: docker

- name: install docker-ce
  yum:
    name: docker-ce
    update_cache: yes

- name: create docker config dir
  file:
    path: /etc/docker
    state: directory

- name: set storage driver
  blockinfile:
    path: /etc/docker/daemon.json
    create: yes
    block: |
      {
        "storage-driver": "devicemapper"
      }
