---
- name: install packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
    update_cache: yes
    cache_valid_time: "{{ docker_engine_cache_valid_time }}"

- name: add docker apt key
  apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    state: present

- name: add docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} {{ docker_engine_release_channel }}'
    filename: docker
    update_cache: yes

- name: install docker-ce
  apt:
    name: docker-ce
    update_cache: yes
    cache_valid_time: "{{ docker_engine_cache_valid_time }}"
