---
- name: install python2-dnf
  raw: dnf install -y python2-dnf

- name: purge old docker packages
  dnf:
    name:
      - docker
      - docker-common
      - container-selinux
      - docker-selinux
      - docker-engine
    state: absent

- name: add docker-ce repository
  yum_repository:
    name: docker-ce
    description: Docker Repository
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: yes
    file: docker

- name: install docker-ce
  dnf:
    name: docker-ce
