---
- name: purge old docker packages
  include: purge-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: install docker ce for ubuntu
  include: install-ubuntu.yml
  when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release >= 16

- name: install docker ce for debian
  include: install-debian.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version >= 8

- name: install docker ce with yum
  include: install-centos.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: install docker engine with dnf
  include: packages-dnf.yml
  when: ansible_pkg_mgr == "dnf"

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started
  when: ansible_virtualization_type != "docker" # don't start docker in docker
