---
- name: install python2-dnf
  raw: dnf install -y python2-dnf

- name: add docker repository (fedora)
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/fedora/$releasever/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    file: docker

- name: install docker-engine (dnf)
  dnf:
    name: docker-engine
