---
- name: add docker repository (centos7)
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    file: docker
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"

- name: install docker-engine (yum)
  yum:
    name: docker-engine
    update_cache: yes
