---
- name: purge old docker packages
  apt:
    name:
      - docker.io
      - lxc-docker
      - docker
      - docker-engine
    state: absent
    purge: yes

- name: remove old docker-engine apt key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: absent
